### ISSUE TITLE
about the c++ layer

### ISSUE THREAD

**Issue by PkuRainBow** [madkn/HistogramLoss#1]
Hi, I am an research intern from Peking University, recently, I find that you have experiement result on the stanford product dataset. I am wondering whether you can offer me the related c++ layer file and prototxt files to repeat your experiments.

Thanks

**Comment by madkn** [comment]
Hello,
I'm planning to publish prototxt and models for Stanford Products, but for now you can use prototxt from the original repository:  https://github.com/rksltnl/Deep-Metric-Learning-CVPR16/tree/master/model
The only thing you should change is the loss layer (as in example for person re-id in /models/cuhk03).

As for implementation, there is only the python one.

**Comment by PkuRainBow** [comment]
@madkn   Could you please offer me the choice for  α and β are hyper-parameters ( Binomial Deviance loss)  on the CUB-birds and Stanford Products dataset ?

**Comment by madkn** [comment]
Hi, I used alpha =  2 and beta =  0.5 for Bin Dev loss
