### ISSUE TITLE
About Slice data

### ISSUE THREAD

**Issue by yang502** [madkn/HistogramLoss#5]
In model/cuhk03,the prototxt use slice layer to output 3 slice_datas.In your paper,your are want to create 3 stream sub-network to input 3 parts of person.
I was wonder the slice_dim :1 just mean you slice image in image channel but not in image height? so the slice data are not slice 3 parts of person ?

**Comment by madkn** [comment]
That's right, I do slicing in the channel axis, because I cut images beforehands and put them into the network as 9-channel images (3 parts stacked together)

**Comment by madkn** [comment]
You can see all the preprocessing steps in: https://github.com/madkn/HistogramLoss/blob/master/validation/data_preprocessing.py
